[[redirects]]
  from = "/v1/*"
  to = "https://abpvlog.onrender.com/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
